#!/usr/bin/env bash
# This script is iterating from 1 through 20, printing "4"&"bad luck from China" on the 4th iteration,
# "9"&"bad luck from Japan", and "17"&"bad luck from Italy".

counter=1

while [ $counter -le 20 ]
do
	case $counter in 
	     4)
		echo "$counter"
		echo "bad luck from China"
		;;
	     9)
		echo "$counter"
		echo "bad luck from Japan"
		;;
	     17)
		echo "$counter"
		echo "bad luck from Italy"
		;;
	     *)
		echo "$counter"
		;;
	esac
	((counter++))
done
	
